<style type="text/css">
body {font-family: sans-serif;}
p, li {letter-spacing: 1px; line-height: 150%;}
h1 {line-height: 150%; letter-spacing: 2px}
code {font-size: 14px;}
</style>

<title>Glidix Kernel Exception Catching</title>
<h1>Kernel Exception Catching</h1>
<p>
Kernel exception catching was introduced to reduce the need for safety tests which are almost certain to succeed. For example, when copying data from kernel to userspace, an application usually passes a valid pointer, so we can do a simple <code>memcpy()</code> with an exception catch - that way, no per-page tests are performed, no locks are involved etc; and if a page fault occurs, the exception gets caught.
</p>

<p>
Everything related to exceptions is declared in <code>&lt;glidix/catch.h&gt;</code>. It is implemented partially in assembly and partially in C.
</p>

<h2>The <code>catch()</code> function</h2>
<p>
The <code>catch()</code> function is used to catch exceptions in the kernel. The function initially returns 0. The calling thread may then perform dangerous operations, and if an exception occurs, execution rewinds back to the <code>catch()</code> call, and instead of returning zero, it returns the exception that occured. If it returns 0, then after performing your protected block, you must call <code>uncatch()</code>. If an exception occurs, <code>uncatch()</code> is called automatically. Here's an example using page faults:
</p>

<pre>
int ex = catch();
if (ex == 0)
{
	// here comes the code that may or may not cause a page fault
	*((int*)0) = 0;
	
	// the protected block ends here so call uncatch()
	uncatch();
}
else if (ex == EX_PAGE_FAULT)
{
	// page fault occured!
	// DO NOT call uncatch()!
	return EFAULT;
}
else
{
	// some other exception occured!
	// again, do NOT call uncatch() since an exception occured.
	return EINVAL;
};
</pre>

<h2>Throwing exceptions - the <code>throw()</code> function</h2>
<p>
The <code>throw()</code> function takes only one argument: the exception to throw. Please note that if nobody is catching exceptions, a <code>throw()</code> results in a kernel panic!
</p>

<pre>
throw(EX_PAGE_FAULT);
</pre>

<h2>Safety</h2>
<p>
Any local variables that are not declared <code>volatile</code> are undefined after an exception is caught.
</p>
